public Class contactRecursiveHelper{
    public static boolean isopportunity=false;
    public static boolean isContactUpdate=false;
    public static boolean isAccountUpdate=false;
    public static boolean isContactBeforeDelete=false;
    public static boolean isContacttrigger=false;
    public static boolean createProjectDocs = false;
    public static boolean AccountTrigger  = false;
    public static boolean smssendingSENDDATEUPDATE  = false;
    public static boolean Updatefeddback = false; 
    public static boolean isUpdateCPProperty = false;
    public static boolean isupdateMasterPayment = false;
    
}