public with sharing class UtilityClassForCommissionForm {
public String ChannelPartnerRegistered {get;set;}
public String RegistrationNumber {get;set;}
public String VendorNumber {get;set;}
public String BrokerageCountry {get;set;}
public String BrokerageCurrency {get;set;}
public String BrokerageCommisionpayble {get;set;}
public String AmountPaybleOnAgreementValue {get;set;}

public Boolean ServiceTaxApplicable {get;set;}
public String ServiceTax {get;set;}
public String TotalPaybleAmount {get;set;}
public String SfdcOfferCode {get;set;}
public String EmployeeId {get;set;}
public String ExistingCustomerUnitId {get;set;}

    public UtilityClassForCommissionForm() {
        
    }
}